#!/bin/bash
CURRENTDATE=`date +"%Y-%m-%d %T"`;
echo $CURRENTDATE;
echo -e >> README.md; 
echo "Commit Number : ";
read N;
echo "## Commit : $N [$CURRENTDATE]" >> README.md;
echo "What-ever u did!! Start updating . . .";

for (( i = 1; i <= 100; i++ )); do
	echo "Line $i: ";
	read R;
	if [[ $R == "" ]]; then
		break;
	fi 
	echo "$i: $R <br>" >> README.md;
done
# echo -e >> README.md;
