#!/bin/bash
echo -e >> README.md;
echo "Add imp note . . ."
echo "Topic";
read Z;
echo "### 🟢 $Z" >> README.md;
echo "Start updating . . .";

for (( i = 1; i <= 100; i++ )); do
	echo "Line $i: ";
	read R;
	if [[ $R == "" ]]; then
		break;
	fi 
	echo "$i: $R<br>" >> README.md;
done