#!/bin/bash
echo -e >> README.md;
echo "Add imp note . . ."
echo "Topic";
read Z;
echo "### 🟢 $Z<br>" >> README.md;
echo "how many lines u want?";
read P;
for (( i = 1; i <= $P; i++ )); do
	echo "Line $i: ";
	read R;
	if [[ $R == "" ]]; then
		break;
	fi 
	echo "$i: $R<br>" >> README.md;
done